### ISSUE TITLE
Is this package unmaintaned?

### ISSUE THREAD

**Issue by AmiZya** [fvlima/drf-viewset-profiler#4]
Hello, 

I was wondering about the status of this package, I tested it using python 3.10 and Django 4.1 and it seems to be working fine but would love to have some support for the recent version.

**Comment by fvlima** [comment]
Hey! There is a time that it hasn't any updates. I confess that I'm far from python for a while, and it would be interesting to update it to reflect the new versions of python and django. 

Feel free to create PRs for this if you want. I will try to do something about this next weeks

**Comment by fvlima** [comment]
@AmiZya I've updated the project to support the django versions supported by the django-rest-framework. Take a loot [here](https://github.com/fvlima/drf-viewset-profiler/pull/5)
